apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: prometheus-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: prom/prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        ports:
        - name: http
          containerPort: 9090
