apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: integration-test
      app.kubernetes.io/name: integration-test-job
    name: integration-test-job
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/component: test
          app.kubernetes.io/instance: integration-test
          app.kubernetes.io/name: integration-test-job
      spec:
        containers:
        - args:
          - --namespaces=prometheus-example
          - --interval=5s
          - --timeout=60s
          image: localhost:5001/integration-test:latest
          name: integration-test-job
          resources: {}
          volumeMounts: []
        initContainers: []
        restartPolicy: OnFailure
        serviceAccountName: integration-test-job
        volumes: []
kind: List
